# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    transport: smtp
    auth_mode: login
    port: 465
    encryption: ssl
    host: mail.jla-dev.com
    username: contact@jla-dev.com
    password: contact@02310
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
    spool: { type: memory }
